### ISSUE TITLE
evaluate/improve how we handle the unique taskid

### ISSUE THREAD

**Issue by spigad** [dmwm/CRABClient#1957]
atm we are caching the unique workflow id in the local filesystem. 
The client take care to map the user known task ID to the unique one.. we need at least  to support the possibility to pass directly the unique task id

**Comment by AndresTanasijczuk** [comment]
Is this issue outdated or is still valid? If the point hare was to allow crab commands to get the task name as input instead of the project directory, then consider that:
- We have the 'crab remake' command which is used to rebuild project directory given a task name. Then the user can pass this project directory as input to the crab commands.
- The advantage of requiring a project directory as input for the crab commands is that in the project directory there is the crab.log file where log messages are written. If we don't have a project directory as reference, we would have to create a new crab.log file at some place (cwd). For user support it is better to have the crab.log file with the history of all crab commands the user executed for the task.

**Comment by mmascher** [comment]
It would be nice to have imho, but it is also very low e priority. Let's
hear other opinions
Il 21/apr/2015 18:09 "Andres Tanasijczuk" <notifications@github.com> ha
scritto:

**Comment by mmascher** [comment]
closing, no user ever found this relevant, and worst case they can do the remake
