### ISSUE TITLE
Crab dry run test

### ISSUE THREAD

**Issue by evansde77** [dmwm/CRABClient#2824]
Add option for user to run a limited test run that truncates the request and tests the workflow by running a few jobs.

Extra credit if it is called crab --appetizer

Expect this will spawn a couple of tickets in WMCore to implement this feature.

**Comment by AndresTanasijczuk** [comment]
I will close this issue as it seems to me it is outdated. Please reopen if you don't agree.
We have now 'crab submit --dryrun' which runs a test job in the client. Then a user can do 'crab proceed' to actually submit the jobs to the grid. This is similar to what is requested in this issue except that the test job doesn't run on the grid. OTOH, the user can always run 1 job only, since he has the totalUnits parameter available. He can send the output to a dummy directory and not publish it. So I think we have all the tools for the user to run a test job by himself. Of course we can ask CRAB to do the job, but should we?
