### ISSUE TITLE
Provide a command to user to trigger the publication of all files ready at a given time

### ISSUE THREAD

**Issue by HassenRiahi** [dmwm/CRABClient#4109]
Moving this ticket https://github.com/dmwm/AsyncStageout/issues/4194 from ASO to the Client.

**Comment by mmascher** [comment]
maybe was done @dciangot can you chrck

**Comment by belforte** [comment]
when discussing this today in ASO review context it was not clear how much it is needed. Starting pint will be a summary (by @dciangot  ) of the flow which ASO uses now to decide when to publish what it has.

An example use case will be:
task almost completed, 67 jobs still to be published but a few jobs have not run yet and likely will not. How do I tell ASO to publish those 67 jobs as well, w/o waiitng to reach count of 100, so that I can take DBS snapshot to prepare a recovery task ?

**Comment by belforte** [comment]
present policy is good enough
