### ISSUE TITLE
Auto completion script improvements

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABClient#4391]
Hi Matthias,

I noticed that since we inctroduced this, I cannot hit tab to complete the directory name. Meaning that if I hit `crab status --dir crab_projects/taskna` and then TAB, I cannot see the directory starting with taskna*. Can you fix it?

Also, I believe the bash script should be automatically generated, we don't want that it gets deprecated when we change the parameters name. Maybe you can provide a script to generate it that I can run when I build the RPMs.

Finally, the `complete` command is not available everywhere, imho we should include it in the RPM and in COMP (and that's on me). See  https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/386/1/1/1.html

**Comment by matz-e** [comment]
Working on something.

The last issue seems to come from users using zsh and relying on bash scripts for environments.  Since this is a true "bashism", options would be to supply a zsh version (more work), or just guard the sourcing of the completion to be done only in bash (this would also help with ksh users, etc).

**Comment by mmascher** [comment]
I would go for guarding the source of the script, and make it available only for bash.

**Comment by matz-e** [comment]
I have a simple auto-generating script (BTW, dynamic introspection with the `SubCommands` is a pain, since they want to build a connection to the server in the constructor).  This still has no fancy this option requires these parameters features or completes directories only where needed (e.g. `-d`).  Where should I stick that?  `bin/`?

Also, I can't really reproduce your issue with the directories.  For me, directories complete fine…

**Comment by mmascher** [comment]
Hi, strange, the autocompletion of the directories works also for me now... Ignore that, maybe something changed on lxplus..

About the other comment, I am not sure what you are asking.. In general I would like to have a directory for the "operators scripts", like in `bin/operators`. I can put the script to create the job wrapper structure I was mentioning in another ticket (Anna said she might go with another solution, so it might be worth to add this script).

Thoughts?

**Comment by matz-e** [comment]
I'd prefer plain `scripts/`, as I'm under the impression that most things in `bin/` will get packaged, and a nested structure always gets a little more complicated.

**Comment by mmascher** [comment]
Reopening, that's a "three (two) issues in one", and I still need to do my part.

**Comment by belforte** [comment]
I really do not know what exactly was left to do here, but since AFAIK autocompletion works. Let's close.
