### ISSUE TITLE
control addition of the directories

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABClient#4398]
we need a parameter to control the addition of the directories

See here : https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/8013.html

**Comment by AndresTanasijczuk** [comment]
The Data.inputFiles parameter also accepts directories. I tested it. This actually means that the new parameter from Marco, JobType.sendPythonFolder, is not really needed... And maybe we have to change the name of the parameter Data.inputFiles because it not only accepts files, but also directories.

**Comment by AndresTanasijczuk** [comment]
Just read this issue again, because I think it is fixed. But do we want to keep the `JobType.sendPythonFolder` parameter around? This parameter is to add the $CMSSW_BASE/python directory to the input sandbox. It defaults to False. 
My doubt on keeping it or not is because one can use the Data.inputFiles to add directories to the sandbox. But maybe folders in the $CMSSW_BASE directory (not in $CMSSW_BASE/src) should be treated separately as we do with `lib`, `biglib`, `module`.

**Comment by annawoodard** [comment]
> But maybe folders in the $CMSSW_BASE directory (not in $CMSSW_BASE/src) should be treated separately as we do with lib, biglib, module.

What is the advantage of treating those folders separately? I like @AndresTanasijczuk's idea of getting rid of the `JobType.sendPythonFolder` parameter if it is redundant with `Data.inputFiles`: the fewer knobs, the better.

On a related but very minor note (probably too minor to be worth the trouble of changing): the name `Data.inputFiles` makes it a little surprising that it accepts directories. I think `Data.userInputs` or `Data.privateInputs` would be better.

**Comment by belforte** [comment]
@matz-e this is little work, but the one to understand the issue and make a clear decisions on what to offer to users to avoid them being confused. I think you are good at this, can you take care ?

**Comment by matz-e** [comment]
Hm…

For the HN message above: Why stick tons of output produced by something in `python/` and then be surprised if the sandbox is too big? That's the same as sticking stuff into `data/` and then having the same problem.

As far as I recall, treating the `python` folder differently from the user specified files makes sense, as it is special. The `inputFiles` end up at the same level as the python folder in the tarball (i.e., the tarball contains `lib`, `python`, `myUserFile`…), **but** they get treated differently in the end, where the user files [get moved to the execution directory](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/WMRuntime/Scripts/UnpackUserTarball.py#L116). Doing this with the python folder will break import stuff CMSSW-style.

I think it makes sense to rename `inputFiles` with `userInputs`, as @annawoodard suggests.

**Comment by belforte** [comment]
I surely agree.
Should we do anything with python subdir then ? Or simply rename the parameter ?

**Comment by matz-e** [comment]
We should not do anything with the python subdir, to not brake things. What I suggest, to have a somewhat consistent namespace:

1. Rename `inputFiles` to `sendUserInputs`
2. keep `sendPythonFolder`
3. Introduce `blacklist` with a default of `['.cvs', '.git', '.svn']`

The latter should be a parameter, to be able to override it for more advanced users, who for whatever (absurd?) reason will need access to version history on a running job.

**Comment by belforte** [comment]
I am not sure we'll even find the time and guts to do this, but... OK. I understand. Assigning to me, no point in bugging others, it is a small improvement on someting that anyhow works.

**Comment by belforte** [comment]
in the end I am for keeping current situation.
