### ISSUE TITLE
inputFiles: document how this is handled

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABClient#4509]
I have got a private feedack from Dima, he was using config.JobType.inputFiles clearly specifying thatthe file was in dir/file.lhe . The file was put in the root direcotry of the sandbox, his point was that this should be at least documented

**Comment by belforte** [comment]
I guess @dciangot will not do it. Do you feel like taking care @emaszs ? Or shall I assign to myself ?

**Comment by emaszs** [comment]
Yep

**Comment by emaszs** [comment]
I wrote a few sentences in the FAQ [1] and added a pointer to the FAQ in the configuration parameter documentation page [2], please let me know if it makes any sense and if there's a more appropriate place to put it.

CRABClient behaves like it does because we add the user files to the sandbox using an arcname [3] which we get with  `os.path.basename(filename)`. This maintains the directory structure in the sandbox if a directory is passed as an input file, though the directory itself is always added to the root. If a file is passed, it will always be added to the root of the sandbox because only the base name is used for it's name in the sandbox. It's probably a necessary evil for cases like when an absolute filename is passed, since it makes no sense to have `afs/cern.ch/user/e/erupeika/supportFiles/PileupData2016B_69200.root` in the sandbox, might as well use the base name instead.

[1]
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ#How_are_the_inputFiles_handled_i
[2]
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile#CRAB_configuration_parameters
[3]
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/JobType/UserTarball.py#L90

**Comment by belforte** [comment]
assign to me to review the documentation and close

**Comment by belforte** [comment]
Marginally modified the twikis referenced above to add a couple examples.
I think it is very clear.
