### ISSUE TITLE
when SiteDB lookup fails there should be a more decent message

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4516]
and surely do not blame CRAB configuration file !
i.e. not:

Syntax error in CRAB configuration file:
Unable to retrieve username from SiteDB: malformed string
followed by a scary traceback

see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/760/1.html

**Comment by AndresTanasijczuk** [comment]
The error originated in the `getUsernameFromSiteDB` function, which the user used in his CRAB configuration file. He must have done something like:
```
from CRABClient.UserUtilities import getUsernameFromSiteDB
...
config.Data.outLFNDirBase = '/store/user/%s/' % (getUsernameFromSiteDB())
...
```

The function `getUsernameFromSiteDB` raised an exception here https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/UserUtilities.py#L91-L100 (because the stdout dictionary had {"login": null, "name": null}). The user did not handle the exception, so it propagated up to the line where the CRAB config is loaded (https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/SubCommand.py#L51). It was then catched in https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/SubCommand.py#L79-L85 as a generic RuntimeError exception and therefore the generic message "Syntax error in CRAB configuration file". The _extractReason() function is there https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/SubCommand.py#L80 to remove stacktrace, but in this case this is part of the exception message already (https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/UserUtilities.py#L95-L99), so it can not be removed.

Possible solutions:
1) Teach (document) how to catch an exception from the `getUsernameFromSiteDB` function in the CRAB config.
2) Catch and handle the exceptions that the function can raise explicitly before this line https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/SubCommand.py#L79

But this issue probably shows that it is not correct to do literal_eval in https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/UserUtilities.py#L92. I think Stefano mentioned once that he would prefer to do the parsing of stdout a la CRAB2 (via shell commands like in https://github.com/dmwm/CRAB2/blob/master/python/check_HN_Name.py#L23). Is that correct @belforte ?

By the way, the stdout/stderr/traceback added in https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/UserUtilities.py#L95-L99 was done in this commit https://github.com/dmwm/CRABClient/commit/dc389f4fdf3f8ce5bb045c21af51d462b7592089 IIRC as response to a request from @belforte (or maybe the request was only for stdout/stderr, and we decided to include traceback with @mmascher)

**Comment by belforte** [comment]
hmmm.. I think I have seen the "Malformed string" also when user do `crab checkusername` and their DN is not known to SiteDB.  This is not limited to users calling  `getUsernameFromSiteDB` in their config.

For what you describe above, I think the only solution is  that in each function which we user can call
(all in ClientUtilities.py ?) we handle all exceptions, and never pass any to the user. I do not understand what you wrote about SubCommand.py, I think I do not know enough about how client works.

The `literal_eval` smells of treating JSON as a python dictionary. Indeed this is not good, expecially if JSON allows null as value and dictionary does not, at least IIUC. Maybe you should use a proper JSON parser, if you do not want to grep and cut, or convert stdout to a string and then parse it with string manipulaiton. But JSON is not a dictionary.
It is sadly true that there are tools which dumps a dictionary and call it "json output", but SiteDB is actually careful and really produces JSON.

Gee, this was a complex explanation that you gave @AndresTanasijczuk , I am not sure I understood, nor whether my reply here is on topic and/or complete/clear. In case let's talk about it face to face next week, possibly looking at the source toghether.

**Comment by AndresTanasijczuk** [comment]
Sure, is true that the "Malformed string" can happen also in `crab checkusername`, since this command uses at the end the `getUsernameFromSiteDB` function. But what you didn't see for sure in that case was the message "Syntax error in CRAB configuration file:". And my previous explanation was intended to make clear why in the case example https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/760/1.html of this issue there was such a message "Syntax error in CRAB configuration file:", given that this is one of the things you complained about:
```
and surely do not blame CRAB configuration file !
i.e. not:

Syntax error in CRAB configuration file:
```

Also, if the error happens in `crab checkusername`, there should have been a decent explanatory message: https://github.com/dmwm/CRABClient/blob/3.3.1510.rc3/src/python/CRABClient/ClientUtilities.py#L506-L509 We can move this message from `getUsernameFromSiteDB_wrapped` to `getUsernameFromSiteDB` to make sure it will also appears when `getUsernameFromSiteDB` is used outside `getUsernameFromSiteDB_wrapped`.

About your statement 
```
I think the only solution is that in each function which we user can call
(all in ClientUtilities.py ?) we handle all exceptions, and never pass any to the user.
```
I remember to have asked in a CRAB3 meeting if raising exceptions in a function that we provide to users (all available in the UserUtilities.py module) was ok, and the conclusion was that yes; that we should only make sure we document what exceptions can be raised by each function, and we leave the responsibility to the user to handle them. I am not against revisiting this.

Just let me clarify also that the client commands are executed inside try/excepts (https://github.com/dmwm/CRABClient/blob/master/bin/crab#L151) which handle the exceptions (writing them to the log file). So if the user uses any function from UserUtilities.py not in a standalone way, but via a `crab <command>` execution, the exception is not left unhandled. In the case of the example of this issue what is confusing is the appearance of a traceback, but as I said, this was added on purpose to the exception message; is not a traceback of an unhandled exception. And I think I remember now why I added the traceback: it was because I was not sure about the literal_eval behavior, so I wanted to have a traceback for debugging purposes.

So, I think the actions to take for this issue summarize to:
1) Handle the JSON returned by SiteDB appropriately (don't use it as an ordinary python dictionary).
2) Don't add the traceback to the (handled) exceptions from `getUsernameFromSiteDB`. The general idea is that tracebacks are only needed for unexpected exceptions.
3) Add a more explanatory message to the UsernameException in `getUsernameFromSiteDB`. Maybe by moving https://github.com/dmwm/CRABClient/blob/3.3.1510.rc3/src/python/CRABClient/ClientUtilities.py#L506-L509 inside `getUsernameFromSiteDB`.
4) Maybe: Catch ProxyException and UsernameException when loading the CRAB config, and don't print in that cases "Syntax error in CRAB configuration file:". I am personally not in favor of doing this; I think is not worth.

**Comment by AndresTanasijczuk** [comment]
Action item 4) is not possible. WMCore catches all exceptions and raises RuntimeError. So instead of 4) I would propose:
5) Change message "Syntax error in CRAB configuration file:" by something more general like "Error while loading CRAB configuration:"

**Comment by belforte** [comment]
OK with 1) 2) 3) 5)

**Comment by AndresTanasijczuk** [comment]
For 1) I decided to go with the CRAB2 style: grep and cut.
