### ISSUE TITLE
check if process.source is in pset

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABClient#4528]
See https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/803/1/2/1/1/1/2/1/1/1.html

**Comment by AndresTanasijczuk** [comment]
This is only needed for 'Analysis' workflows, right?

**Comment by AndresTanasijczuk** [comment]
Actually I submitted a PrivateMC task without defining process.source and it fails with that same error. So I guess we have to do the check for both, 'Analysis' and 'PrivateMC'.

**Comment by AndresTanasijczuk** [comment]
But should CRAB do such kind of validation of the CMSSW config at all?

**Comment by bbockelm** [comment]
I think it's reasonable to have CRAB do validation if it's straightforward to implement, has no false positives, and based on support incidents.

**Comment by ericvaandering** [comment]
+1 Of course, no check should be done for scriptExe workflows.

**Comment by mmascher** [comment]
Hi,

just few comments since I was not convinced about this.

I see that the error is there also for montecarlo as well. I took this PSet: https://raw.githubusercontent.com/dmwm/CRABServer/master/test/templates/config/psets/pset_tutorial_MC_generation.py

and commented out this line:

```
#process.source = cms.Source("EmptySource")
``` 

The pset loads correctly when it is imported but `process.source` is `None`:

```
>>> import pset_tutorial_MC_generation
>>> print pset_tutorial_MC_generation.process.source
None
```

And cmsRun fails miserably:

```
----- Begin Fatal Exception 29-Jul-2015 20:53:58 CEST-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
Exception Message:
There must be exactly one source in the configuration.
It is missing (or there are sufficient syntax errors such that it is not recognized as the source)
----- End Fatal Exception -------------------------------------------------
```

So I would say that the fix definitely easy (an `if self.fullConfig.process.source is not None` here https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/JobType/CMSSWConfig.py#L60) and I do not think there are false positive if we excluded scriptExe: it seems there is no way cmsRun can succed unless we set an input source.

Sorry for the long comment, but I wanted to document everything also for the benefit of @belforte who Justas said was not convinced by this as well.

**Comment by belforte** [comment]
let me explain my postion, then you do as you like.
I am all for helping users on things we do not them to learn about, like CRAB internals, HTCondor, GSI, X059, Grid etc. BUt when it comes to a mistake in Pset which they can spot doing the test we always recommend to run their conifg interactively and only happened once in ten years... I'd save the effort to even think about it.
Better to improve Crab status reporting, which still manages to confuse many.

**Comment by ericvaandering** [comment]
Let me explain mine. CRAB modifies this part of the users config but doesn't check that what it wants to modify is present. That's a bug in any program. This isn't just a sanity check on the users config.

I don't care, really, if the check is done in the client or in the runtime, but something like 

  File "/home/pilcms047/home_cr008_268520122/CREAM268520122/glide_MgXDou/execute/dir_22118/WMCore.zip/WMCore/WMRuntime/Scripts/SetupCMSSWPset.py", line 133, in fixupFileNames
AttributeError: 'NoneType' object has no attribute 'fileNames'

isn't user or programmer friendly. Much better to try/except this and generate a real error message (and yeah, if we "fix" this at Runtime this is a WMCore issue, not strictly CRAB3).

**Comment by belforte** [comment]
+1

**Comment by AndresTanasijczuk** [comment]
What do you exactly mean by excluding scriptExe workflows? Because if the scriptExe includes running cmsRun, then we still have to validate the CMSSW config, right? Or by scriptExe you had in mind workflows that run a user script that doesn't include cmsRun? Can we base the decision of doing the validation or not on whether the psetName was given in the CRAB config? It's True that currently the psetName is required even if the scriptExe doesn't include a call to cmsRun, but this is another story we should fix IMO.

**Comment by ericvaandering** [comment]
scriptExe may or may not have a PSet but I don't see how it's CRAB's responsibility to validate it.

**Comment by AndresTanasijczuk** [comment]
Then for you the ONLY reason for validating the PSet is what you said before "CRAB modifies this part of the users config but doesn't check that what it wants to modify is present" (IOW, if CRAB wouldn't modify anything in the PSet you wouldn't do any validation)? In that case, should we move this issue to WMCore?

**Comment by belforte** [comment]
Yes, your last comment correctly describes it: the code (in WMCore?) which modifies Pset should print a better message when it tries to manipulate some line which is missing but really expected.
Validating the Pset is a different thing, which has a ill defined, and possibly very large scope. I'd rather make it part of "allow user to run one job interactively and do their debugging".

**Comment by ericvaandering** [comment]
Can you 

a) post a summary of what was decided today in the meeting
b) create a WMCore issue to improve this? I will assign it to Andres.

**Comment by AndresTanasijczuk** [comment]
I think this is what we decided:

1) When running scriptExe, it should not be mandatory to provide a PSet in the CRAB config (currently it is).
2) When running scriptExe, if a PSet is provided tweak it in the way it is done now; if a PSet is not provided skip the tweak.
3) If (and only if) a PSet is provided in the CRAB config, do a basic validation of it (so far basic validation means to check process.source is not None).

**Comment by belforte** [comment]
My summary of the discussion would be a bit different, even if mostly with same action items, let me record it here:
1. pset manipulation happens as a consequence of data discovery and job splitting to put the proper input for each job. 
2. when user specify scriptExe, nothing change other than instead of running cmsRun the wrapper runs the user's exe (with some proper arguments).
3. as a consequence of 1. and 2. the manipulation (and therefore error checking) of user Pset is the same wheather scritpExe was used or not
4. we will not try to validate scriptExe. This is for the user. But if manipulation of it fails, it must be reported in such a way to help figuring out the problem,
5. when using scriptExe the user must be given the possibility of not specify a Pset (therefore no  manipulation must be attempted, and this must not rise error). Of course input splitting will stil be done and the input files/lumi list for each job must be passed to the user's script in some way.  In the meeting it was mentioned (extract the input list from the manipulated Pset), that's no good.

**Comment by belforte** [comment]
this is labelled as Done. Can it be closed ?

**Comment by belforte** [comment]
AFAICT the work to be done is now tracked in: https://github.com/dmwm/WMCore/issues/6095
can keep this open as a reminder.

**Comment by AndresTanasijczuk** [comment]
https://github.com/dmwm/WMCore/issues/6095 is now merged. Closing this issue.
