### ISSUE TITLE
Add command to change dataset/file status in DBS

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABClient#4551]

**Comment by belforte** [comment]
those commands are now available[*], although not in the $PATH, I am not sure  what's the best way to make them available w/o typing he path.
My personal preference would be for @yuyiguo to move them fro 'examples' to 'bin' in the DBS Client repository. So it will all work transparently, since cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/bin is already in the $PATH after CRAB3 is setup.

[*]
belforte@lxplus0029/~> ls /cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/examples/DBS3Set*
/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/examples/DBS3SetDatasetStatus.py*
/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc481/cms/dbs3-client/3.2.114/examples/DBS3SetFileStatus.py*
belforte@lxplus0029/~>

**Comment by AndresTanasijczuk** [comment]
This is the documentation we are providing so far: https://twiki.cern.ch/twiki/bin/view/CMSPublic/Crab3DataHandling#Changing_a_dataset_or_file_statu 
So we are telling users to run 
`python $DBS3_CLIENT_ROOT/examples/DBS3Set[Dataset,File]Status.py`

**Comment by belforte** [comment]
thx. I did not know that crab(3).sh defines  $DBS3_CLIENT_ROOT. This is OK then.

**Comment by AndresTanasijczuk** [comment]
Good. Can we close this issue then?
