### ISSUE TITLE
give warning about diff output filenames

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABClient#4584]
I checked yesterdays failures and from most of them is Output file not found. In particular this could be improved at this place:
https://github.com/dmwm/CRABClient/blob/b77a65d26cd9833d75de64f65b4cd1990aa52660/src/python/CRABClient/JobType/Analysis.py

There it already get information about which files will be produced from pset. All should be good if not users specifying outputFiles. 
```
ERROR: Output file HiForest.root does not exist.
Output file HiForestAOD.root exists.
```
There is already a print which files will be collected, so warning at this point will not help :/ Maybe explicitly give red message warning: 'WARNING: In your pset there is defined %s files, but in crab configuration you specified %s. Please ignore this message if you think everything is correct. Otherwise, please kill your task and modify as needed.'

I would be more drastic and would force them to write input, like 'yes/no' which he confirms that he double checked and everything is correct. 

We need to teach them :)

**Comment by belforte** [comment]
It is a nasty issue. Questions are not good since a very large fraction of usage is via scritps which either wrap crab CLI or use crabAPI. An option which says "I know I want a file which is not listed in my PSet" is likely to end up in being set by default by everybody simply because "it helped  someone some time ago and anyhow it is the example I got".
There is only so much teaching we can do with an effective gain/pain ratio.

I am currently inclined to put this in the big category:  look into lowering priority of all jobs in a task if a significant fraction of jobs are failing. Rather than look for some ad hoc improvements to this particular issue.
