### ISSUE TITLE
Allow to purge the cache area if the state is submitted

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABClient#4596]
It is not possible now: https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/purge.py#L52-L55

**Comment by belforte** [comment]
odd that nobody else noticed yet. We just added SUBMITFAILED !
anyhow, I am doing this now.

**Comment by belforte** [comment]
Note needed changes from PR

    Only clean the user cache by default.
    Clean up the 'if' statement logic of handling the options, now the ifs are opposite of intuitive.
    If the option to clean the schedd is specified, don't allow tasks in the 'SUBMITTED' status to be purged

**Comment by belforte** [comment]
@mmascher @emaszs and @belforte had a small discussion about this.
We need to make it more clear if purge command is aksing for crab cache to be purged (what user need now) or schedd (which we never had to so far).
Clearly only crab file cache can be purged cavalierly for a SUBMITTED task.
We agreed to rewrite a bit the code so that the logic is more clear at the same time.

**Comment by belforte** [comment]
at the same time we could address #4566

**Comment by belforte** [comment]
we will deprecate purge after moving to S3 for cache
