### ISSUE TITLE
not handled exception 

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4630]
in
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/JobType/Analysis.py#L181
you should not only assign msg and go on, but likely you want to log the msg and then need to tale some action (raise again or... whatever).
It happened to me that the previous `debugFilesUploadResult = dtb.upload(filecacheurl = filecacheurl)` fails (maybe I have not found the proper combination to make new client work in my private test area...) but then client dies with:
```
UnboundLocalError: local variable 'debugFilesUploadResult' referenced before assignment
```
at next line

separately I (we?) have to investigate why the upload fails. I have updated code in the server and restarted crabcache and crabserver, have updated Oracle.. yet:
```
The server answered with an error.
Server answered with: Input file hashkey mismatch
Reason is: Checksums do not match
```

**Comment by emaszs** [comment]
I don't think raising anything else is necessary if the upload fails - the client and server should be fine without it. The monitor would not fully work in that case, but that's fine. I'll make a PR for handling the exception properly.

**Comment by belforte** [comment]
worth a test, maybe I did something wrong, but I think the server will
complain if it does not find the debug sandbox (at least I got an error
which I attributed to that)

On 07/06/2016 10:32 AM, Emilis Rupeika wrote:
> I don't think raising anything else is necessary if the upload fails - the client and server should
> be fine without it. The monitor would not fully work in that case, but that's fine. I'll make a PR
> for handling the exception properly.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dmwm/CRABClient/issues/4630#issuecomment-230711127>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABwK2Q_QtFSX4_mD69ZsTKQWZHo083Gvks5qS2g5gaJpZM4JFmDE>.
>

-- 
Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by emaszs** [comment]
The server checks if the file exists before copying it to the webdir: https://github.com/dmwm/CRABServer/pull/5236/files#diff-3fa1996a22a9c377b41882d6cf77ab1cR198
It also checks before attempting to download the tarball from the crabcache: https://github.com/dmwm/CRABServer/pull/5236/files#diff-87c8bab9e7cf28a8e8b0526de0cbed82R882
Another check before trying to extract it's contents: https://github.com/dmwm/CRABServer/pull/5236/files#diff-87c8bab9e7cf28a8e8b0526de0cbed82R824. If the tarball doesn't exist, the server will try to extract the files out of the sandbox, because they are likely to be there since the previous clients didn't have this new tarball. If that fails, it will add a warning but not stop the overall execution. That's my understanding anyway.
