### ISSUE TITLE
avoid to divide by zero when no jobs have run

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4753]
latest crab status versio crashed like this
```
ERROR 2018-04-10 14:07:16,291: 	 Unhandled Exception!
ERROR 2018-04-10 14:07:16,291: 	 division by zero
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1804/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1804/bin/crab", line 148, in __call__
    self.cmd()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1804/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 139, in __call__
    self.printDetails(statusCacheInfo, self.jobids, True, maxMemory, maxJobRuntime, numCores)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1804/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 472, in printDetails
    cpu_ave = (cpu_sum / run_sum)
ZeroDivisionError: division by zero
ERROR 2018-04-10 14:07:16,299: 	 ERROR: ZeroDivisionError: division by zero
```
see
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/3741.html

**Comment by hernand** [comment]
By the way, when calculating the avg/max/min statistics, maybe only successful jobs should be taken into account. Some jobs might fail very early and bias the RAM/CPU statistics to very low values

**Comment by hernand** [comment]
well, I think the statistics warn people when the requested RAM is excessive or when the CPU efficiency is too poor. Jobs that fail at the beginning for any reason are going to bias the statistics towards lower values. I would remove those outliers from the calculations which aim at informing the user about RAM consumption and CPU efficiency in the steady state. 

CPU efficiency is more difficult to interpret, because there might be reason outside user's control for a low cpu efficiency (slow storage, remote reads)... I would put a low threshold for CPU efficiency to trigger the warning, say 50%. With that threshold you already catch the case where more than 1 core is requested and only 1 used, e.g.

**Comment by belforte** [comment]
this will be a never ending topic. We will always need to revisit what exactly we report in light of exprience and the fact that problems of the day/month/year change in time.
So rather than going into exactyl what to do when each metric has a certain value, and try to make all logic fits in one line I'd separate the code into steps:
- collect info (silent)
- report summary (always)
- warn (point user to improve things)
- complain (make it clear user NEED to take action)
But I'd rather not do that in this issue or PR and keep things simple now, even if clearly not optimal.
The attempt to do all with one sigle if and have those values array is brave, but maybe things are already starting to be too complex for it being easy to read, something more verbose but more clear may be easier to maintain. But this is the cost of coding first and design later.

Let's not try to be perfect.
As a start:
- Wall time used vs. requested: warning if used < 30% of requested saying "your jobs may run sooner if you fix this"
- CPU Efficiency :  warn if below 50% for the task, all in, warn about #threads if below 30% and cores>1
- RAM: warn if request higher than default and use < 70%

And leave complains for later.

Overall it is better to keep text here very short and point to CRAB3 FAQ where we can use a few lines to say things like if you use little walltime because jobs failed, fix the error.

**Comment by hernand** [comment]
I agree, Stefano. All I say is: in the calculations do not use jobs that failed at the beginning, because the values of walltime, cpu eff and RAM are not representative and will bias the statistics. Maybe instead of removing all failed jobs, only jobs that failed at startup (walltime less than 5 minutes?) could be removed. This would keep those jobs e.g. killed for going beyond the max runtime. 
Anyway, just a suggestion.

**Comment by lecriste** [comment]
@belforte, [this](https://github.com/dmwm/CRABClient/commit/bb95a73) commit tunes the CPU efficiency message as requested.
The PR #4754 can be merged from my side.

**Comment by belforte** [comment]
OK. Let's merge this and worry later about moving hints etc. to the twiki
