### ISSUE TITLE
Import Rucio python api in CRABClient

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABClient#4850]
Needed to perform rucio checks before submission

**Comment by belforte** [comment]
let's be careful not to increase dependencies of CRAB Client. We are trying hard to actually reduce them. A different story is for TaskWorker, where a good check of Rucio things is surely possible.

**Comment by dciangot** [comment]
mmm, so you suggest to move everything to tw side?

**Comment by belforte** [comment]
1. TW **must** do a check
2. Client **could** do a check if there's a way to do it which does not make our lives more difficult. E.g fork a CLI, rather than import unclear dependencies. If dependencies are clear, simple, stable, well understood... etc.et. can talk about it, but surely need to avoid that submissions that have nothing to do with Rucio fail because Rucio client import fails. Just look at how much pain was the DAS python client before Valenting came up with a static executable.

**Comment by dciangot** [comment]
agreed and move to CRABServer repo all the relevant issues. 

I don't see much that can be done without pain and safely on client side at this point. So I'm closing this.

**Comment by belforte** [comment]
is rucio client such a terrible beast ? I was hoping that it has a CLI which we can call like we do for voms-proxy-* or gfal-copy.  Well at least on TW we have full control of the env. and no need to be compatible with CMSSW.

**Comment by dciangot** [comment]
CMSSW compatibility convinced me to move it in the TW actually + no reason to risk breaking non Rucio things for client Rucio dependency.

**Comment by belforte** [comment]
IN an any case users should be given a way to check things from their end. Should not need to submit a crab task to find out that their quota is full. Let's revisit once those procedures are defined and established.

**Comment by dciangot** [comment]
mmm, for that I think that they better use rucio client directly and nothing integrated into CRAB client.

**Comment by belforte** [comment]
maybe all that CrabCient will do is to print a message asking them to check. Let' see once it is clear what exacly means "use rucio client directly" and what kind of support CMS will have for it.

**Comment by belforte** [comment]
Rucio client is not compatible with CMSSW. Whatever we need to do, we do via forking a Rucio CLI command like done currently inside checkwrite command
