### ISSUE TITLE
replace calls to DBS Python client with dasgoclient

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABClient#4870]
since usage for DBS calls in CRAB Client is very limited (only used to build list of lumis in input dataset for crab recovery command), it will be better use dasgoclient which is more portable and a better fit for new distribution inside CMSSW since it is already used e.g. inside cmsDriver

@vkuznet @smuzaffar @lecriste @yuyiguo any comment ? Do you agree that this is good ?
It is not urgent, but I think it will be easy for me to do.

This means that we will stop distributing DBS Python client together with CRAB and people who needs it will have to check coide out of github and use an environment (like current CMSSW or COMP) with  good SSL and cJson libraries.

Well.. we could keep DSB Client there, but since CRAB will not use it, it makes little sense and will only confuse people working on maintaining this years from now.

**Comment by vkuznet** [comment]
Stefano, I think it is a good idea. Since dasgoclient is static executable, does not require any setup and provides/support DAS QL, it is easier to use on a client side. It also does not required DAS server meaning that it will only do HTTP requests to underlying systems. So, on my side I would say it makes sense and will make system easy to use and maintain.

**Comment by yuyiguo** [comment]
You may want to keep DBS client with Crab client until I can distribute a DBS client. I don't think it is a good idea to ask the users to checkout from github.

**Comment by belforte** [comment]
Thanks Yuyi. I did not know that you had plans to distributed DBS Python client. That will help a lot. Do you have a sense of the time line ? WIll this be a "pip install dbs" or what ?

The thing is that we are moving to a simplified distribution of CRAB Client "as a set of python files inside CMSSW" [1] and while currently Shahzad magic makes DBS Client code appear in the right place, it does not pull in e.t. the scripts in other places than src/python in github, like l`DBS3SetDatasetStatus.py`
https://github.com/dmwm/DBS/blob/master/Client/utils/DataOpsScripts/DBS3SetDatasetStatus.py

One important use case for DBS Client in user land is to manage user datasets, as per https://twiki.cern.ch/twiki/bin/view/CMSPublic/Crab3DataHandling#Changing_a_dataset_or_file_statu
W/o an explicit DBS Client distribution, user would be left with pulling those from git.

But I see as really important for us to move to a ligther way to distribute CRAB Client.

I wonder if we could have this 'for free' is simply DBS/Client/utils where  a subfolder of /DBS/CLient/src/python but I guess that you do not want to contemplace major reshuffling in DBS code.

[1]
https://github.com/dmwm/CRABClient/issues/4844

**Comment by yuyiguo** [comment]
Hi Stefano,

I had no plans to distributed DBS Python client separately from crab client until I saw your message.  I don't think it is a good idea to have the user to put from github so something gets to be done!
@smuzaffar, Any suggestion what should be done for DBS client?
@amaltaro , You or Erik worked on pip install for WMAgent ? How was it? Maybe I could learn from your guys?

I am open for suggestions.
Thanks,
Yuyi

**Comment by belforte** [comment]
Sorry to create problems for you Yuyi.  We can surely keep the dependency listed in the spec file even if CRAB Client itself does not call DBS, it may confuse people who may be maintaining this after we'll be gone, that's all.
Let's hear from Shahzad and Alan, I but all in all you my want to think about moving utils folder under python/src

**Comment by yuyiguo** [comment]
Not a problem, Stefano. We will find a way to do this. And you will support/develop crab for the foreseeable future, right?

You are asking DBS client to include the utils that are the DBS API examples. I will see if we can have the new distribution to include the utils directory too instead of moving it under src.

**Comment by amaltaro** [comment]
If dasgoclient can be restricted to only one data source (DBS), in order to fetch this list of lumis, then I think it makes sense to stick with dasgoclient and stop using DBSClient from within the crabclient environment.
However, if dasgoclient would make requests to multiple data sources (dbs, phedex, reqmgr2, mcm), then indeed a see room for some improvement.

**Comment by belforte** [comment]
From DAS documentation:
DAS has a several special keywords: system, date, instance, records.
    The system keyword is used to retrieve a records only from specified system (data-service), e.g. DBS.
so I am assuming that dasgoclient --query="lumis dataset=blah system=DBS" or something similar will do
anyhow this is not very important anymore, sine I am not going to remove dependency from DBS Client and CJSON.

**Comment by vkuznet** [comment]
For the record,
dasgoclient ALWAYS talk to a single data-source, that's why it is fast, it does
not perform aggregation as DAS server does.

The data-source is based on DAS query, if query requires DBS dasgoclient will
go to DBS, if query requires Phedex dasgoclient will talk to phedex. For
queries which are supplied by different systems, e.g. block info, I have
defaults in dasgoclient, see https://github.com/dmwm/dasgoclient/blob/master/main.go#L241
and I use fail-over chain approach, e.g.
file queries first looked up in DBS, if no files found then phedex is used.

In 95-99% of the cases the fail-over chain is not used because primary
data source provides the data.

**Comment by belforte** [comment]
see also https://github.com/dmwm/CRABClient/issues/4844#issuecomment-577397042
using DBS Client brings in WMCore DBSReader as well and hence the new retry decorator

**Comment by belforte** [comment]
@vkuznet 
I started to look into replacing dasgoclient to calls to DBSReader in CRAB Client.

Is the dasgoclient output format documented (especially the JSON) one ?

I am looking for the list of lumis in a dataset, and I get something like this [*]

so the output seems a list of dictionaries (one per run number ?)
each with these keys
```
In [7]: lumilist[0].keys()                                                                                                                 
Out[7]: dict_keys(['das', 'lumi', 'qhash', 'run'])
```
but `lumilist[0]['lumi']` is not a simple list of lumis, but a list of dictionaries.
and same for `lumilist[0]['run']`
The latter is a bit confusing, if there's one element for run, why does it have a
list of run numbers ?

And in any case this is not any of the formats supported by the standard
CMS LumiList class 
https://github.com/cms-sw/cmssw/blob/master/FWCore/PythonUtilities/python/LumiList.py

So may questions are:

Q1: is the current format documented, so that instead of guessing the structure by
 inspecting the output, I can use a sure reference to build my dictionary ?

Q2: is a method available already (would be great!) to turn the dasgoclient output
into one standard LumiList object ? in particular it would be great a t have a compact
representation with [1,100] indicating a range instead of a list of the 1..100
numbers in random order. see https://github.com/cms-sw/cmssw/blob/1ddd87ea1129455d5a8773cc4ecd7bb2af35cc81/FWCore/PythonUtilities/python/LumiList.py#L25-L31 


Q3: is there guarantee that the output format will never change ?

Q4: may I trust the shell return value of dasgoclient to tell error situations ? I.e. if
 return value is 0 I can use the stdout w/o further validation ?

Thanks
Stefano



[*]
```
In [1]: import subprocess 
   ...:                                                                                                                                    

In [2]: query="dasgoclient --query 'run,lumi dataset=/SingleMu/Run2011B-WMu-19Nov2011-v1/RAW-RECO'  --json"                                

In [3]: import json                                                                                                                        

In [4]: out=subprocess.check_output(query, shell=True)                                                                                     

In [5]: lumilist=json.loads(out)                                                                                                           

In [6]: lumilist[0]                                                                                                                        
Out[6]: 
{'das': {'expire': 1579733031,
  'instance': 'prod/global',
  'primary_key': 'run.run_number',
  'record': 1,
  'services': ['dbs3:run_lumi4dataset']},
 'lumi': [{'number': [1,
    12,
    23,

more lines..

    54,
    56,
    4]}],
 'qhash': '957eb8983509e1530224bc47184bee89',
 'run': [{'run_number': 178041}]}

In [7]:                                               
```

**Comment by vkuznet** [comment]
Stefano, you asked plenty of questions therefore I'll place answers one by one by cut-and-paste your question first. Here it goes:

**_Is the dasgoclient output format documented (especially the JSON) one ?_**
DAS uses JSON as output data format, the content of of the JSON is service/API dependent, but DAS follows these rules:
- user provide a query, e.g. `file dataset=XYZ`, the `file` is a look-up key, while `dataset=XYZ` is condition
  - if user query only consists of condition then its key is used as lookup key, e.g. `dataset=XYZ`, here look-up key is `dataset` and condition is `dataset=XYZ`
- DAS provide output for every look-up key as key value in a JSON data output, where each key will have attribute name, e.g. `file` key has `name` attribute. Therefore the data will be either presented as `file:{name: <value>}` or if output is an array of values `file:[{name:<value>}, {name:>value>}]` 
Said that the rest of the output is API dependent. If service API provides more attributes they will be placed into look-up key sub-dictionary. For example `dataset=/ZMM*/*/*` query will provide this output:
```
dasgoclient -query="dataset=/ZMM*/*/*" -json
...
{"das":{"expire":1579788382,"instance":"prod/global","primary_key":"dataset.name","record":1,"services":["dbs3:datasets"]},
"dataset":[{"acquisition_era_name":"RunIIFall18GS","create_by":"wmagent@vocms0280.cern.ch","created_by":"wmagent@vocms0280.cern.ch","creation_date":1570776114,"creation_time":1570776114,"data_tier_name":"GEN-SIM","dataset_access_type":"VALID","dataset_id":13956459,"datatype":"mc","last_modification_date":1571859872,"last_modified_by":"cmsunified@vocms0268.cern.ch","modification_time":1571859872,"modified_by":"cmsunified@vocms0268.cern.ch","name":"/ZMM_13TeV_TuneCP5-pythia8/RunIIFall18GS-SNB_HP_102X_upgrade2018_realistic_v17-v2/GEN-SIM","physics_group_name":"NoGroup","prep_id":"MUO-RunIIFall18GS-00028","primary_dataset.name":"ZMM_13TeV_TuneCP5-pythia8","primary_ds_name":"ZMM_13TeV_TuneCP5-pythia8","primary_ds_type":"mc","processed_ds_name":"RunIIFall18GS-SNB_HP_102X_upgrade2018_realistic_v17-v2","processing_version":2,"status":"VALID","xtcrosssection":null}],
"qhash":"a23301d90474354ea00f8dd44c62c6b2"}
```
Moreover, each DAS JSON output provides additional sections in JSON dictionary, the `das` section contains meta-data about DAS query itself, e.g. the expiration timestamp, `primary_key` (this is your first look-up key of the query on which DAS performs construction of output record), etc. And, appropriate query hash called `qhash`.

All mapping of DAS keys and services APIs are provided in [DAS maps](https://github.com/dmwm/das2go/blob/master/maps) repository. If you'll open concrete service yaml file you'll see how it is structured. Each API section has lookup key, followed by das_map which provides `das_key` (this what users use in DAS QL) and associated `rec_key` which is what look-up name I mentioned above and also corresponding service API parameter called `api_arg`.

**_output of complex queries_**
In case of complex queries where multiple look-up keys are provided, e.g.
`run,lumi dataset=/SingleMu/Run2011B-WMu-19Nov2011-v1/RAW-RECO`
DAS follows the same convention, each look-up key is represented as individual entry in JSON dictionary, in this case you have `run` and `lumi` keys in JSON. Each key leads to its own list of records which are dicts. For `run` records you have each record with structure `{run_number:<value>}` and for `lumi` each record is `{number:<value>}`. If there are multiple records they will either be aggregated by services and split into individual DAS records. In that case you have output of multiple records:
```
{"das":{"expire":1579788888,"instance":"prod/global","primary_key":"run.run_number","record":1,"services":["dbs3:run_lumi4dataset"]},
"lumi":[{"number":[97,...]}],
"run":[{"run_number":175906}]}
...
{"das":{"expire":1579788888,"instance":"prod/global","primary_key":"run.run_number","record":1,"services":["dbs3:run_lumi4dataset"]},
"lumi":[{"number":[97,...]}],
"run":[{"run_number"::177074]}
```
As you can see each records contains one run and associated list of lumis for that run. This is done because run,lumis are associated with each file (and internally DAS/DBS look-up triplets of file,run,lumis).

DAS does not provide short format for lumis. If you need it your client should do this job. DAS tasks is to look-up data across distributed services and provide aggregation. Since these operations are quite expensive, all others "convenient" tasks are left to the client.

Now to be concrete on you Q questions:
Q1: yes DAS has its structure, I explained it above
Q2: No, the client can do this
Q3: DAS formats is not changing since DAS deals with many services and apply the same set of rules to all of them, changing a format will be a huge headache. But you need to learn DAS format as I explained above since its structure and logic chosen to accommodate plethora of formats, naming convention presented in CMS services APIs.
Q4: das returns proper error codes, see
```
./dasgoclient -exitCodes
DAS exit codes:
1 DAS error
2 DBS upstream error
3 PhEDEx upstream error
4 Rucio upstream error
5 Dynamo upstream error
6 ReqMgr upstream error
7 RunRegistry upstream error
8 McM upstream error
9 Dashboard upstream error
10 SiteDB upstream error
11 CRIC upstream error
12 CondDB upstream error
13 Combined error
14 MongoDB error
15 DAS proxy error
16 DAS query error
17 DAS parser error
18 DAS validation error
```
But you also be paranoid and check `das` section of the output which will give more information about error (if it happens).

And, in general, you should study help (option `-h`) section of DAS as it will provide you plenty of information, e.g. `-daskeys` Show supported DAS keys, `-exitCodes` Show DAS error codes, `-examples` Show examples of supported DAS queries, etc.

**Comment by belforte** [comment]
Thanks @vkuznet that's all I need and more. I am all set.
