### ISSUE TITLE
Outdated twiki help links and getUsernameFromSiteDB -> getUsernameFromCRIC

### ISSUE THREAD

**Issue by clelange** [dmwm/CRABClient#4901]
I was trying to submit grid jobs, but querying SiteDB fails. The output suggested the following:

> Note: Make sure you have the correct certificate mapped in SiteDB (you can check what is the certificate you currently have mapped in SiteDB by searching for your name in https://cmsweb.cern.ch/sitedb/prod/people). For instructions on how to map a certificate in SiteDB, see https://twiki.cern.ch/twiki/bin/viewauth/CMS/SiteDBForCRAB.

The latter twiki is decommissioned as well and forwards to https://twiki.cern.ch/twiki/bin/view/CMSPublic/UsernameForCRAB. This twiki also relies heavily on SiteDB as well as the suggested crab commands:
I e.g. ran `crab checkusername` and it shows the same issue:
`Failed to get username from SiteDB`

I then searched this forum for possible related issues and found https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5590.html as well as https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5576.html - SiteDB has been decommissioned.

I went further down the rabbit hole and I guess the bottom line is that
- crab needs to be fixed so that `getUsernameFromSiteDB()` simply calls to `getUsernameFromCRIC` (and therefore https://cms-cric.cern.ch/) and the latest valid twiki pages. I used the latest version available on LXPLUS and this doesn't seem to be the case. With SiteDB decommissioned this would allow old scripts to continue working.
- Also, the UsernameForCRAB twiki needs to be cleaned of everything related to SiteDB. Further, the links at the top of that twiki page pointing to https://twiki.cern.ch/twiki/bin/viewauth/CMS/CRICForCRAB don't work since this twiki doesn't exist (and I couldn't find it using the twiki search to fix it myself).

I saw #4899 but I'm not sure this is already being addressed there.
I hope you don't mind me posting this here rather than on computing tools hypernews where this has already been discussed in several places.

**Comment by belforte** [comment]
thanks a  lot @clelange and sorry for being late in replying.
I am afraid that we really need to make people remove *SiteDB* calls from their script.
I can put a dummy function which prints a warning, but scripts will stay broken. Such extensive usage if getUsername* in user scripts was not anticipated, and hence I can't back fix this.
The way CRAB client is deployed makes it very cumbersome to push changes quickly.
Which is part of why I am moving to the new way of deploying via CMSSW where at
least there's the possibility to use the Integration Build which is updated nightly.

I will surely address the problems with the twiki. Thanks for pointing it out.

Finally, crab checkusername tells you that it fails to talk to SiteDB, but in the end works.
I do no see anything to fix there.

If you want to conclude that when SiteDB was turned off there was nobody available to
make a new version of CRAB in 24h or less to make it almost transparent for users... that's indeed the truth. I am the only one editing CRAB code, and that's not the only thing I am doing.
After a few days of "its broken" and people having changed SiteDB --> CRIC.. I do not see the point in spending more work.
My aim now is to future proof things by making users change from getUsernameFromCRIC to getUsername, period. Since the CRIC way may not work in the new non-certificate-based authentication world.

**Comment by belforte** [comment]
I believe that I have fixed the twiki page
https://twiki.cern.ch/twiki/bin/view/CMSPublic/UsernameForCRAB
please let me know of any further problems with CRAB twikis

**Comment by clelange** [comment]
Thank you, the twiki page is much improved!
