### ISSUE TITLE
remove automatic log uploading

### ISSUE THREAD

**Issue by ddaina** [dmwm/CRABClient#4993]
in light of replacing `UFC` with `S3`, we should remove automatic log upload in:
https://github.com/dmwm/CRABClient/blob/a5c9b457d1981cba649f8b63f6a631ef1eb83297/bin/crab#L121-L132
there is no way to access info if cache is `S3` or old `UFC` and  upload log file to `S3` from this code. exceptions should be catched while inside crab sub-command execution and crab uploadlog should be used then.

**Comment by belforte** [comment]
otherwise, in the spirit of the original implementation, we would need to find or setup some "public drop box" where log files can be posted with minimal requirements on the uploader.

But this will only be needed if `crab uploadlog` can not be used, i.e. CRABServer unreacheable, or crab client failing early inside crab submit. For both we can simply ask users to send long by mail or similar. Chances of genuine bugs in CRAB Client code are much reduced after years of running and stability of the code.
