### ISSUE TITLE
make crab-dev submit tasks to preprod instead of prod as default

### ISSUE THREAD

**Issue by ddaina** [dmwm/CRABClient#5075]
in attempt to make `crab-dev` work with `python3` and `CMSSW_12`, we should make submissions to `crab-dev` client submit tasks to `preprod` instance instead of `prod` as default. this will allow users submit to `crab-dev` without changing their configuration files.

first of all need to investigate what changes are needed at all.

**Comment by ddaina** [comment]
so the relevant code is here:

https://github.com/dmwm/CRABClient/blob/96861e2291555f7939f5d82fc86e6de68263eed2/src/python/CRABClient/Commands/SubCommand.py#L388-#L422

and to be even more precise, `prod` as default value is set here:
https://github.com/dmwm/CRABClient/blob/96861e2291555f7939f5d82fc86e6de68263eed2/src/python/CRABClient/ClientMapping.py#L67

It currently works in the following way:

1. If user use `--instance` option in `crab submit` command, then task is submitted to that instance regardless of the fact that `crabConfig.py` has `instance` set;
1. If user has `instance` set in `crabConfig.py` and does not use `--instance` option in `crab submit` command, then task is submitted to `instance` specified in `crabConfig.py` 
1. If user does not have `instance` attribute set in `crabConfig.py` file and does not use `--instance` option in `crab submit` command, then task is automatically submitted to `prod`;

@belforte, we initially talked about use case number 3 - when user does not have  `instance` attribute set in `crabConfig.py` and does not use `--instance` option in `crab submit` command, we should submit to `preprod`. What should we do if user:

1. uses `crab-dev` and have `instance` set in `crabConfig.py` to smth that is not equal to `preprod`;
1. uses `crab-dev` and set `crab submit` option `--instance` to smth that is not equal to `preprod`?

**Comment by belforte** [comment]
thanks @ddaina  for having sorted this out.
If there is an explicit request for a different instance, either via config file or command option, we should respect it, if nothing else, to allows us to test all combinations !
So we leave 1. and 2. as they are and only change 3. to submit to preprod instead of prod.
I.e. we only change this line
https://github.com/dmwm/CRABClient/blob/96861e2291555f7939f5d82fc86e6de68263eed2/src/python/CRABClient/ClientMapping.py#L67

Of course .. we never trust Stefano, and always test !
